version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
    ports:
      - "8081:80" # Exposed on port 8081 to avoid conflict with Jenkins
    depends_on:
      - backend
